# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Catatan MangSi untuk Nusantara
email: info@negeripelangi.com
description: > # this means to ignore newlines until "baseurl:"
  "Jika seseorang meninggal dunia, maka terputuslah amalannya kecuali tiga perkara (yaitu): sedekah jariyah, ilmu yang dimanfaatkan, atau do’a anak yang sholeh" (HR. Muslim no. 1631)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mangsi.negeripelangi.org" # the base hostname & protocol for your site
twitter_username: negeripelangi
instagram_username:  negerialquran
facebook_username: NegeriAlQuran

# Build settings
markdown: kramdown
